#!/bin/bash
git clone https://github.com/heisedebaise/ranch.git && \
git clone https://github.com/beanshell/beanshell.git && \
git clone https://github.com/alibaba/easyexcel.git && \
git clone https://github.com/kaltura/KalturaGeneratedAPIClientsAndroid.git && \
git clone https://github.com/zdavatz/AmiKo-Android.git && \
git clone https://github.com/zhangdaiscott/jeecg-boot.git && \
git clone https://github.com/GoogleCloudPlatform/storage-sdrs.git && \
git clone https://github.com/CenturyLinkCloud/mdw.git && \
git clone https://github.com/yu120/neural.git && \
git clone https://github.com/NationalSecurityAgency/ghidra.git && \
git clone https://github.com/rememberber/WePush.git && \
git clone https://github.com/UNIZAR-30246-WebEngineering/lab1-git-race.git && \
git clone https://github.com/Subterranean-Security/Sandpolis.git && \
git clone https://github.com/googleapis/java-spanner.git && \
git clone https://github.com/zhongxunking/configcenter.git && \
git clone https://github.com/dipoo/egdownloader.git && \
git clone https://github.com/JoeZ-EE/LeetCodeSolutionsInJavaAndCpp.git && \
git clone https://github.com/zdila/gpx-animator.git && \
git clone https://github.com/kkrull/javaspec.git && \
git clone https://github.com/youlookwhat/CloudReader.git && \
git clone https://github.com/DaveVoorhis/Relang.git && \
git clone https://github.com/googleapis/google-api-java-client-services.git && \
git clone https://github.com/GenweiWu/Blog.git && \
git clone https://github.com/saki4510t/libcommon.git && \
git clone https://github.com/ia-toki/judgels.git && \
git clone https://github.com/tensorics/tensorics.github.io.git && \
git clone https://github.com/youngmonkeys/ezyfox.git && \
git clone https://github.com/quarkusio/quarkus.git && \
git clone https://github.com/redkale/redkale.git && \
git clone https://github.com/alibaba/Sentinel.git && \
git clone https://github.com/Library-of-Kaeon/Library-of-Kaeon.git && \
git clone https://github.com/EpiCanard/GlobalMarketChest.git && \
git clone https://github.com/xiaojinzi123/Component.git && \
git clone https://github.com/dataloom/conductor-client.git && \
git clone https://github.com/didi/DoraemonKit.git && \
git clone https://github.com/elunez/eladmin.git && \
git clone https://github.com/xuebaofeng/intellij-idea-config.git && \
git clone https://github.com/google/framework-for-osdu.git && \
git clone https://github.com/GoogleCloudPlatform/gcp-token-broker.git && \
git clone https://github.com/didclab/onedatashare.git && \
git clone https://github.com/Tristan971/EasyFXML.git && \
git clone https://github.com/treason258/TreLibrary.git && \
git clone https://github.com/google/graphicsfuzz.git && \
git clone https://github.com/oswetto/LoboEvolution.git && \
git clone https://github.com/firebase/firebase-android-sdk.git && \
git clone https://github.com/sergmain/aiai.git && \
git clone https://github.com/alibaba/nacos.git && \
git clone https://github.com/Alex1304/ultimategdbot.git && \
git clone https://github.com/manuel3108/Gleisbelegung.git && \
git clone https://github.com/retest/recheck.git && \
git clone https://github.com/seata/seata.git && \
git clone https://github.com/zhanaotian/AndroidStudioSettings.git && \
git clone https://github.com/dataloom/datastore.git && \
git clone https://github.com/langhsu/mblog.git && \
git clone https://github.com/GoogleCloudPlatform/cloud-opensource-java.git && \
git clone https://github.com/orioncode/orionplatform.git && \
git clone https://github.com/cheng2016/developNote.git && \
git clone https://github.com/digammas/damas.git && \
git clone https://github.com/EricJoosse/Integrador-Sistemas-com-PortalCronos-para-Fornecedores.git && \
git clone https://github.com/google/ground-android.git && \
git clone https://github.com/burakbayramli/kod.git && \
git clone https://github.com/skeychen/dswork.git && \
git clone https://github.com/pepstock-org/Charba.git && \
git clone https://github.com/GoogleContainerTools/jib.git && \
git clone https://github.com/bk138/multivnc.git && \
git clone https://github.com/lsst-uk/phymatopus.git && \
git clone https://github.com/b3dgs/warcraft-remake.git && \
git clone https://github.com/Betalord/BHBot.git && \
git clone https://github.com/ist-dsi/fenixedu-id-cards.git && \
git clone https://github.com/David-Development/ownCloud-Account-Importer.git && \
git clone https://github.com/kaltura/KalturaGeneratedAPIClientsJava.git && \
git clone https://github.com/intuit/QuickBooks-V3-Java-SDK.git && \
git clone https://github.com/jonathanlermitage/manon.git && \
git clone https://github.com/xuxueli/xxl-job.git && \
git clone https://github.com/authlete/authlete-java-common.git && \
git clone https://github.com/Nasdanika/html.git && \
git clone https://github.com/sirixdb/sirix.git && \
git clone https://github.com/BookFrank/CodePlay.git && \
git clone https://github.com/carlos-sancho-ramirez/android-java-langbook.git && \
git clone https://github.com/i-net-software/JWebAssembly.git && \
git clone https://github.com/yidongnan/grpc-spring-boot-starter.git && \
git clone https://github.com/ccem-dev/otus-api.git && \
git clone https://github.com/peerkar/liferay-gsearch.git && \
git clone https://github.com/Twasi/twasi-core.git && \
git clone https://github.com/cisco-system-traffic-generator/trex-java-sdk.git && \
git clone https://github.com/cismet/cids-distribution-wuppertal.git && \
git clone https://github.com/gudaoxuri/dew.git && \
git clone https://github.com/facebook/litho.git && \
git clone https://github.com/ist-dresden/composum-platform.git && \
git clone https://github.com/pousse-cafe/pousse-cafe.git && \
git clone https://github.com/BrightSpots/rcv.git && \
git clone https://github.com/googleads/googleads-mobile-android-mediation.git && \
git clone https://github.com/jeanpetric/drummer.git && \
git clone https://github.com/bonigarcia/selenium-jupiter.git && \
git clone https://github.com/phoenixctms/ctsms.git && \
git clone https://github.com/giloutho/Logfly.git && \
git clone https://github.com/danschultequb/qub-java.git && \
git clone https://github.com/Nincodedo/Ninbot.git && \
git clone https://github.com/bazelbuild/bazel-buildfarm.git && \
git clone https://github.com/softelnet/sponge.git && \
git clone https://github.com/onemoonsci/nmrfxprocessor.git && \
git clone https://github.com/ligoj/bootstrap.git && \
git clone https://github.com/hheg/jitstatic.git && \
git clone https://github.com/snowflakedb/snowflake-jdbc.git && \
git clone https://github.com/tabish121/proton4j.git && \
git clone https://github.com/technecloud/cronapi-java.git && \
git clone https://github.com/bitrich-info/xchange-stream.git && \
git clone https://github.com/adridadou/eth-propeller-core.git && \
git clone https://github.com/Sp2000/colplus-backend.git && \
git clone https://github.com/williamfiset/Algorithms.git && \
git clone https://github.com/stevespringett/Alpine.git && \
git clone https://github.com/kubernetes-client/java.git && \
git clone https://github.com/sormuras/bach.git && \
git clone https://github.com/pkiraly/metadata-qa-marc.git && \
git clone https://github.com/Kotori316/QuarryPlus.git && \
git clone https://github.com/maruTA-bis5/mattermost4j.git && \
git clone https://github.com/sodash/open-code.git && \
git clone https://github.com/Taskana/taskana.git && \
git clone https://github.com/CognizantOneDevOps/Insights.git && \
git clone https://github.com/zsmartsystems/com.zsmartsystems.zigbee.git && \
git clone https://github.com/gmessner/gitlab4j-api.git && \
git clone https://github.com/GoldRenard/JuniperBotJ.git && \
git clone https://github.com/crnk-project/crnk-framework.git && \
git clone https://github.com/ligoj/plugin-prov.git && \
git clone https://github.com/Adyen/adyen-java-api-library.git && \
git clone https://github.com/opensds/nbp.git && \
git clone https://github.com/Flash3388/FlashLib.git && \
git clone https://github.com/wcm-io-qa/wcm-io-qa-galenium.git && \
git clone https://github.com/lanhuaguizha/Christian.git && \
git clone https://github.com/oitsjustjose/Geolosys.git && \
git clone https://github.com/mirkosertic/Bytecoder.git && \
git clone https://github.com/Col-E/Recaf.git && \
git clone https://github.com/manifold-systems/manifold.git && \
git clone https://github.com/uweschaefer/factcast.git && \
git clone https://github.com/reasonml-editor/reasonml-idea-plugin.git && \
git clone https://github.com/curioswitch/curiostack.git && \
git clone https://github.com/Sriee/epi.git && \
git clone https://github.com/datastax/java-driver.git && \
git clone https://github.com/Aquerr/EagleFactions.git && \
git clone https://github.com/PDXFinder/pdxfinder.git && \
git clone https://github.com/jaffa-projects/jaffa-framework.git && \
git clone https://github.com/spring-cloud-incubator/spring-cloud-gateway.git && \
git clone https://github.com/Erudika/scoold.git && \
git clone https://github.com/HedvigInsurance/bot-service.git && \
git clone https://github.com/IntegratedAlarmSystem-Group/ias.git && \
git clone https://github.com/elixir-no-nels/trackfind.git && \
git clone https://github.com/spring-cloud/spring-cloud-gcp.git && \
git clone https://github.com/schwabdidier/GazePlay.git && \
git clone https://github.com/nhsconnect/careconnect-reference-implementation.git && \
git clone https://github.com/NoraUi/NoraUi.git && \
git clone https://github.com/yahoo/athenz.git && \
git clone https://github.com/yangfuhai/jboot.git && \
git clone https://github.com/dernasherbrezon/r2cloud.git && \
git clone https://github.com/rsksmart/rskj.git && \
git clone https://github.com/nikita36078/J2ME-Loader.git && \
git clone https://github.com/chrisj42/minicraft-plus-revived.git && \
git clone https://github.com/gorkem/java-language-server.git && \
git clone https://github.com/google/tink.git && \
git clone https://github.com/networknt/light-codegen.git && \
git clone https://github.com/OpenLiberty/open-liberty.git && \
git clone https://github.com/BiglySoftware/BiglyBT.git && \
git clone https://github.com/yegor256/cactoos.git && \
git clone https://github.com/aws/aws-sdk-java-v2.git && \
git clone https://github.com/junkerm/specmate.git && \
git clone https://github.com/remkop/picocli.git && \
git clone https://github.com/aika-algorithm/aika.git && \
git clone https://github.com/TulevaEE/onboarding-service.git && \
git clone https://github.com/zoff99/ToxAndroidRefImpl.git && \
git clone https://github.com/all-of-us/workbench.git && \
git clone https://github.com/wso2/product-ei.git && \
git clone https://github.com/micrometer-metrics/micrometer.git && \
git clone https://github.com/OmniKryptec/OmniKryptec-Engine.git && \
git clone https://github.com/intuit/karate.git && \
git clone https://github.com/Shadorc/Shadbot.git && \
git clone https://github.com/MCMrARM/revolution-irc.git && \
git clone https://github.com/realityforge/arez.git && \
git clone https://github.com/BBVA/mirrorgate.git && \
git clone https://github.com/intranda/goobi-viewer-core.git && \
git clone https://github.com/google/j2cl.git && \
git clone https://github.com/freeplane/freeplane.git && \
git clone https://github.com/indy256/codelibrary.git && \
git clone https://github.com/katsuster/ememu.git && \
git clone https://github.com/wso2/security-tools.git && \
git clone https://github.com/nimble-platform/identity-service.git && \
git clone https://github.com/bazelbuild/intellij.git && \
git clone https://github.com/RohanNagar/thunder.git && \
git clone https://github.com/confluentinc/common.git && \
git clone https://github.com/OpenVidu/openvidu.git && \
git clone https://github.com/jenkinsci/plugin-compat-tester.git && \
git clone https://github.com/danigiri/morfeu.git && \
git clone https://github.com/voyages-sncf-technologies/hesperides.git && \
git clone https://github.com/renyuneyun/Easer.git && \
git clone https://github.com/craftercms/deployer.git && \
git clone https://github.com/gravitee-io/graviteeio-access-management.git && \
git clone https://github.com/nikiroo/fanfix.git && \
git clone https://github.com/codenvy/che.git && \
git clone https://github.com/SES-fortiss/SmartGridCoSimulation.git && \
git clone https://github.com/wcm-io/wcm-io-wcm.git && \
git clone https://github.com/Blankj/AndroidUtilCode.git && \
git clone https://github.com/dvarrui/libro-de-actividades.git && \
git clone https://github.com/ihongs/HongsCORE.git && \
git clone https://github.com/NLCR/komplexni-validator.git && \
git clone https://github.com/ngageoint/geopackage-mapcache-android.git && \
git clone https://github.com/ARIG-Robotique/robots.git && \
git clone https://github.com/DBCG/cqf-ruler.git && \
git clone https://github.com/ppatierno/kaas.git && \
git clone https://github.com/StevenUpForever/LeetCode_Java.git && \
git clone https://github.com/seratch/jslack.git && \
git clone https://github.com/google/mug.git && \
git clone https://github.com/GerritCodeReview/plugins_quota.git && \
git clone https://github.com/xenit-eu/dynamic-extensions-for-alfresco.git && \
git clone https://github.com/objective-solutions/taskboard.git && \
git clone https://github.com/researchstudio-sat/webofneeds.git && \
git clone https://github.com/blackducksoftware/hub-common.git && \
git clone https://github.com/Mashape/unirest-java.git && \
git clone https://github.com/fkzhang/WechatUnrecalled.git && \
git clone https://github.com/jinahya/bit-io.git && \
git clone https://github.com/hedzr/android-file-chooser.git && \
git clone https://github.com/ultraq/redhorizon.git && \
git clone https://github.com/wcm-io/wcm-io-handler.git && \
git clone https://github.com/YuKitAs/tech-note.git && \
git clone https://github.com/skylot/jadx.git && \
git clone https://github.com/apache/commons-vfs.git && \
git clone https://github.com/wcm-io/wcm-io-tooling.git && \
git clone https://github.com/nidi3/graphviz-java.git && \
git clone https://github.com/ymback/NGA-CLIENT-VER-OPEN-SOURCE.git && \
git clone https://github.com/JMRI/EngineDriver.git && \
git clone https://github.com/msaperst/selenified.git && \
git clone https://github.com/actiontech/dble.git && \
git clone https://github.com/PCLuddite/baxshops.git && \
git clone https://github.com/shopizer-ecommerce/shopizer.git && \
git clone https://github.com/gbif/crawler.git && \
git clone https://github.com/asdf2014/yuzhouwan.git && \
git clone https://github.com/NGSEP/NGSEPcore.git && \
git clone https://github.com/mickleness/pumpernickel.git && \
git clone https://github.com/athrane/bassebombecraft.git && \
git clone https://github.com/whiskeysierra/compass.git && \
git clone https://github.com/oliexdev/openScale.git && \
git clone https://github.com/Tamaized/AoV.git && \
git clone https://github.com/wso2-extensions/identity-inbound-auth-oauth.git && \
git clone https://github.com/anylineorg/anyline.git && \
git clone https://github.com/gradlman/SensorLib.git && \
git clone https://github.com/wmixvideo/nfe.git && \
git clone https://github.com/bwaldvogel/mongo-java-server.git && \
git clone https://github.com/aoindustries/aoserv-client.git && \
git clone https://github.com/NLeSC/Xenon-examples.git && \
git clone https://github.com/bridgedb/BridgeDb.git && \
git clone https://github.com/leapcode/bitmask_android.git && \
git clone https://github.com/Apicurio/apicurio-studio.git && \
git clone https://github.com/c2mon/c2mon.git && \
git clone https://github.com/dbeaver/dbeaver.git && \
git clone https://github.com/authorjapps/zerocode.git && \
git clone https://github.com/REBOOTERS/AndroidAnimationExercise.git && \
git clone https://github.com/Jasig/NotificationPortlet.git && \
git clone https://github.com/McLeodMoores/starling.git && \
git clone https://github.com/maxcom/lorsource.git && \
git clone https://github.com/jamesagnew/hapi-fhir.git && \
git clone https://github.com/CodeforLeipzig/lvz-viz.git && \
git clone https://github.com/kite9-org/k9.git && \
git clone https://github.com/opitzconsulting/orcas.git && \
git clone https://github.com/freefair/gradle-plugins.git && \
git clone https://github.com/Nearsoft/google-code-jam.git && \
git clone https://github.com/awsdocs/aws-doc-sdk-examples.git && \
git clone https://github.com/MSG134/IVCT_Framework.git && \
git clone https://github.com/Mindgamesnl/OpenAudioMc.git && \
git clone https://github.com/Netflix/conductor.git && \
git clone https://github.com/spring-cloud/spring-cloud-contract.git && \
git clone https://github.com/confluentinc/rest-utils.git && \
git clone https://github.com/wcm-io/wcm-io-testing.git && \
git clone https://github.com/celandro/pokebattler-fight.git && \
git clone https://github.com/venkatramanm/swf-all.git && \
git clone https://github.com/rroart/stockstat.git && \
git clone https://github.com/bg1bgst333/Sample.git && \
git clone https://github.com/genonbeta/TrebleShot.git && \
git clone https://github.com/metaborg/jsglr.git && \
git clone https://github.com/Samourai-Wallet/samourai-wallet-android.git && \
git clone https://github.com/spinnaker/halyard.git && \
git clone https://github.com/centic9/github-version-statistics.git && \
git clone https://github.com/palantir/gradle-baseline.git && \
git clone https://github.com/ZFGCCP/ZFGC3.git && \
git clone https://github.com/fr3ts0n/AndrOBD.git && \
git clone https://github.com/ZUGFeRD/mustangproject.git && \
git clone https://github.com/cacheflowe/haxademic.git && \
git clone https://github.com/apollographql/apollo-android.git && \
git clone https://github.com/telstra/open-kilda.git && \
git clone https://github.com/matrix-org/matrix-android-sdk.git && \
git clone https://github.com/apache/incubator-tinkerpop.git && \
git clone https://github.com/box/mojito.git && \
git clone https://github.com/judovana/jenkins-scm-koji-plugin.git && \
git clone https://github.com/GerritCodeReview/plugins_reviewers.git && \
git clone https://github.com/GateNLP/gateplugin-python.git && \
git clone https://github.com/madgik/exareme.git && \
git clone https://github.com/triathematician/blaisemath.git && \
git clone https://github.com/spinnaker/echo.git && \
git clone https://github.com/antest1/kcanotify.git && \
git clone https://github.com/javamelody/javamelody.git && \
git clone https://github.com/alibaba/dubbo.git && \
git clone https://github.com/BroadleafCommerce/BroadleafCommerce.git && \
git clone https://github.com/sanaehirotaka/logbook-kai.git && \
git clone https://github.com/simlar/simlar-android.git && \
git clone https://github.com/bonigarcia/webdrivermanager.git && \
git clone https://github.com/reportportal/service-authorization.git && \
git clone https://github.com/SiLeBAT/FSK-Lab.git && \
git clone https://github.com/networknt/light-4j.git && \
git clone https://github.com/hartwigmedical/hmftools.git && \
git clone https://github.com/M66B/NetGuard.git && \
git clone https://github.com/Cognifide/APM.git && \
git clone https://github.com/krs-world/bridges.git && \
git clone https://github.com/Bernardo-MG/tabletop-dice-java.git && \
git clone https://github.com/spinnaker/kork.git && \
git clone https://github.com/xvik/dropwizard-guicey.git && \
git clone https://github.com/raydac/mvn-golang.git && \
git clone https://github.com/wso2-extensions/identity-inbound-provisioning-scim2.git && \
git clone https://github.com/reportportal/commons-model.git && \
git clone https://github.com/resilience4j/resilience4j.git && \
git clone https://github.com/GluuFederation/oxCore.git && \
git clone https://github.com/labsai/EDDI.git && \
git clone https://github.com/projectbuendia/buendia.git && \
git clone https://github.com/carrot2/carrot2.git && \
git clone https://github.com/zielu/GitToolBox.git && \
git clone https://github.com/finmath/finmath-lib.git && \
git clone https://github.com/javaito/HolandaCatalinaFw.git && \
git clone https://github.com/JetBrains/jdk8u_jdk.git && \
git clone https://github.com/google/science-journal.git && \
git clone https://github.com/nzilbb/ag.git && \
git clone https://github.com/GerritCodeReview/plugins_replication.git && \
git clone https://github.com/jenkinsci/analysis-model.git && \
git clone https://github.com/cping/LGame.git && \
git clone https://github.com/HabitatMap/AirCastingAndroidClient.git && \
git clone https://github.com/GoogleCloudPlatform/bigdata-interop.git && \
git clone https://github.com/cucumber/cucumber.git && \
git clone https://github.com/realityforge/replicant.git && \
git clone https://github.com/ram-on/SkyTube.git && \
git clone https://github.com/asciidoctor/asciidoctor-intellij-plugin.git && \
git clone https://github.com/jenkinsci/ec2-plugin.git && \
git clone https://github.com/Wilm0r/giggity.git && \
git clone https://github.com/database-rider/database-rider.git && \
git clone https://github.com/Albertus82/EarthquakeBulletin.git && \
git clone https://github.com/rzwitserloot/lombok.git && \
git clone https://github.com/bmwcarit/joynr.git && \
git clone https://github.com/naver/ngrinder.git && \
git clone https://github.com/cloudiator/lance.git && \
git clone https://github.com/aterai/java-swing-tips.git && \
git clone https://github.com/EgonOlsen71/basicv2.git && \
git clone https://github.com/bdezonia/zorbage.git && \
git clone https://github.com/reportportal/commons-dao.git && \
git clone https://github.com/Mantaro/MantaroBot.git && \
git clone https://github.com/spotify/styx.git && \
git clone https://github.com/zaproxy/zaproxy.git && \
git clone https://github.com/wcmc-its/ReCiter.git && \
git clone https://github.com/jerkar/jerkar.git && \
git clone https://github.com/BrassGoggledCoders/SteamAgeRevolution.git && \
git clone https://github.com/Geforce132/SecurityCraft.git && \
git clone https://github.com/drumonii/LeagueTrollBuild.git && \
git clone https://github.com/jolie/jolie.git && \
git clone https://github.com/HubSpot/jinjava.git && \
git clone https://github.com/cucumber/cucumber-jvm.git && \
git clone https://github.com/ursjoss/scipamato.git && \
git clone https://github.com/thelastpickle/cassandra-reaper.git && \
git clone https://github.com/biblelamp/JavaExercises.git && \
git clone https://github.com/Esri/arcgis-runtime-samples-android.git && \
git clone https://github.com/klehmann/domino-jna.git && \
git clone https://github.com/craftercms/studio2.git && \
git clone https://github.com/ATLauncher/ATLauncher.git && \
git clone https://github.com/TelefonicaED/liferaylms-portlet.git && \
git clone https://github.com/apache/helix.git && \
git clone https://github.com/apache/incubator-asterixdb.git && \
git clone https://github.com/codenameone/CodenameOne.git && \
git clone https://github.com/as-ideas/crowdsource.git && \
git clone https://github.com/zalando/tracer.git && \
git clone https://github.com/tim-group/tg-eventstore.git && \
git clone https://github.com/real-logic/simple-binary-encoding.git && \
git clone https://github.com/alibaba/canal.git && \
git clone https://github.com/EBIvariation/eva-ws.git && \
git clone https://github.com/web3j/web3j.git && \
git clone https://github.com/jpaulm/drawfbp.git && \
git clone https://github.com/ChrisRM/material-theme-jetbrains.git && \
git clone https://github.com/gchq/stroom.git && \
git clone https://github.com/iotaledger/iri.git && \
git clone https://github.com/JetBrains/intellij-sdk-docs.git && \
git clone https://github.com/dreamhead/moco.git && \
git clone https://github.com/EnFlexIT/AgentWorkbench.git && \
git clone https://github.com/census-instrumentation/opencensus-java.git && \
git clone https://github.com/TGAC/miso-lims.git && \
git clone https://github.com/apache/jmeter.git && \
git clone https://github.com/automatictester/lightning.git && \
git clone https://github.com/pinterest/secor.git && \
git clone https://github.com/ontodev/robot.git && \
git clone https://github.com/rsahlin/graphics-by-opengl.git && \
git clone https://github.com/EBIBioSamples/biosamples-v4.git && \
git clone https://github.com/helyho/Voovan.git && \
git clone https://github.com/jooby-project/jooby.git && \
git clone https://github.com/vert-x3/vertx-auth.git && \
git clone https://github.com/opensourceBIM/BIMserver.git && \
git clone https://github.com/bozaro/git-as-svn.git && \
git clone https://github.com/clulab/processors.git && \
git clone https://github.com/axkr/symja_android_library.git && \
git clone https://github.com/alpha-asp/Alpha.git && \
git clone https://github.com/TEAMMATES/teammates.git && \
git clone https://github.com/CruGlobal/android-gto-support.git && \
git clone https://github.com/neowu/core-ng-project.git && \
git clone https://github.com/jdmonin/JSettlers2.git && \
git clone https://github.com/osivia/osivia-portal.git && \
git clone https://github.com/straumat/blockchain2graph.git && \
git clone https://github.com/SpineEventEngine/todo-list.git && \
git clone https://github.com/zalando/problem-spring-web.git && \
git clone https://github.com/apache/servicemix-bundles.git && \
git clone https://github.com/songzhw/AndroidAdvanced.git && \
git clone https://github.com/apache/zookeeper.git && \
git clone https://github.com/bengtmartensson/IrpTransmogrifier.git && \
git clone https://github.com/wayshall/onetwo.git && \
git clone https://github.com/camueller/SmartApplianceEnabler.git && \
git clone https://github.com/4treesCH/strolch.git && \
git clone https://github.com/CreativeMD/LittleTiles.git && \
git clone https://github.com/box/box-android-share-sdk.git && \
git clone https://github.com/bitcoinj/bitcoinj.git && \
git clone https://github.com/stripe/stripe-java.git && \
git clone https://github.com/PhilippC/keepass2android.git && \
git clone https://github.com/segler-alex/RadioDroid.git && \
git clone https://github.com/ehcache/ehcache3.git && \
git clone https://github.com/sklintyg/statistik.git && \
git clone https://github.com/JNOSQL/diana.git && \
git clone https://github.com/jcryptool/crypto.git && \
git clone https://github.com/MarginallyClever/Robot-Overlord-App.git && \
git clone https://github.com/ElvisResearchGroup/L42.git && \
git clone https://github.com/InformaticsMatters/squonk.git && \
git clone https://github.com/mapfish/mapfish-print.git && \
git clone https://github.com/CCI-MIT/XCoLab.git && \
git clone https://github.com/indeedeng/proctor.git && \
git clone https://github.com/cheng-li/pyramid.git && \
git clone https://github.com/3dcitydb/importer-exporter.git && \
git clone https://github.com/BiBiServ/bibigrid.git && \
git clone https://github.com/FabioZumbi12/RedProtect.git && \
git clone https://github.com/apache/samza.git && \
git clone https://github.com/axelor/axelor-business-suite.git && \
git clone https://github.com/scribejava/scribejava.git && \
git clone https://github.com/archimatetool/archi.git && \
git clone https://github.com/arianne/stendhal.git && \
git clone https://github.com/fhoeben/hsac-fitnesse-fixtures.git && \
git clone https://github.com/vector-im/riot-android.git && \
git clone https://github.com/etomica/etomica.git && \
git clone https://github.com/subes/invesdwin-util.git && \
git clone https://github.com/jamesdbloom/mockserver.git && \
git clone https://github.com/phax/ph-oton.git && \
git clone https://github.com/pentaho/pentaho-hadoop-shims.git && \
git clone https://github.com/yahoo/pulsar.git && \
git clone https://github.com/thm-projects/arsnova-backend.git && \
git clone https://github.com/talsma-ict/umldoclet.git && \
git clone https://github.com/UH-StudentServices/mystudies-myteaching-backend.git && \
git clone https://github.com/Transkribus/TranskribusCore.git && \
git clone https://github.com/Scarsz/DiscordSRV.git && \
git clone https://github.com/wso2/carbon-identity-framework.git && \
git clone https://github.com/aricneto/TwistyTimer.git && \
git clone https://github.com/square/keywhiz.git && \
git clone https://github.com/steinarb/ukelonn.git && \
git clone https://github.com/aws/aws-sdk-java.git && \
git clone https://github.com/wso2-extensions/identity-inbound-auth-saml.git && \
git clone https://github.com/belaban/JGroups.git && \
git clone https://github.com/apache/skywalking.git && \
git clone https://github.com/ghedlund/phon.git && \
git clone https://github.com/cuba-platform/cuba.git && \
git clone https://github.com/VoIPGRID/vialer-android.git && \
git clone https://github.com/reflectoring/coderadar.git && \
git clone https://github.com/firebirdberlin/nightdream.git && \
git clone https://github.com/Aeronica/mxTune.git && \
git clone https://github.com/Cognifide/AET.git && \
git clone https://github.com/Longri/cachebox3.0.git && \
git clone https://github.com/DataVault/datavault.git && \
git clone https://github.com/akvo/akvo-flow-mobile.git && \
git clone https://github.com/itachi1706/CheesecakeUtilities.git && \
git clone https://github.com/palantir/atlasdb.git && \
git clone https://github.com/sklintyg/rehabstod.git && \
git clone https://github.com/bbottema/simple-java-mail.git && \
git clone https://github.com/mit-cml/appinventor-sources.git && \
git clone https://github.com/crispab/codekvast.git && \
git clone https://github.com/CloudSlang/score.git && \
git clone https://github.com/DigitalCampus/oppia-mobile-android.git && \
git clone https://github.com/mcMMO-Dev/mcMMO.git && \
git clone https://github.com/dadoonet/fscrawler.git && \
git clone https://github.com/spring-io/initializr.git && \
git clone https://github.com/bhecquet/seleniumRobot.git && \
git clone https://github.com/adaptris/interlok.git && \
git clone https://github.com/BjerknesClimateDataCentre/QuinCe.git && \
git clone https://github.com/openbase/bco.bcozy.git && \
git clone https://github.com/zalando/logbook.git && \
git clone https://github.com/industrial-data-space/trusted-connector.git && \
git clone https://github.com/eMoflon/emoflon-ibex.git && \
git clone https://github.com/reactor/reactor-netty.git && \
git clone https://github.com/wordpress-mobile/WordPress-Android.git && \
git clone https://github.com/zalando/riptide.git && \
git clone https://github.com/TNG/ArchUnit.git && \
git clone https://github.com/jenkinsci/kubernetes-plugin.git && \
git clone https://github.com/graphql-java/graphql-java.git && \
git clone https://github.com/spring-projects/spring-framework.git && \
git clone https://github.com/stefan-niedermann/nextcloud-notes.git && \
git clone https://github.com/Flipkart/foxtrot.git && \
git clone https://github.com/runelite/runelite.git && \
git clone https://github.com/kiegroup/kie-wb-common.git && \
git clone https://github.com/spring-cloud/spring-cloud-sleuth.git && \
git clone https://github.com/luwrain/luwrain.git && \
git clone https://github.com/Panda-Programming-Language/Panda.git && \
git clone https://github.com/msmobility/silo.git && \
git clone https://github.com/kermitt2/grobid.git && \
git clone https://github.com/denkbar/step.git && \
git clone https://github.com/henrichg/PhoneProfilesPlus.git && \
git clone https://github.com/dimagi/commcare-android.git && \
git clone https://github.com/martykan/forecastie.git && \
git clone https://github.com/gbif/registry.git && \
git clone https://github.com/airsonic/airsonic.git && \
git clone https://github.com/google/closure-templates.git && \
git clone https://github.com/mediathekview/MediathekView.git && \
git clone https://github.com/korpling/ANNIS.git && \
git clone https://github.com/glyptodon/guacamole-client.git && \
git clone https://github.com/danrien/projectBlue.git && \
git clone https://github.com/christian-schlichtherle/neuron-di.git && \
git clone https://github.com/raydac/netbeans-mmd-plugin.git && \
git clone https://github.com/synyx/urlaubsverwaltung.git && \
git clone https://github.com/opencb/biodata.git && \
git clone https://github.com/conveyal/gtfs-lib.git && \
git clone https://github.com/camunda/camunda-bpm-platform.git && \
git clone https://github.com/benchdoos/WeblocOpener.git && \
git clone https://github.com/haifengl/smile.git && \
git clone https://github.com/bengtmartensson/harctoolboxbundle.git && \
git clone https://github.com/folio-org/raml-module-builder.git && \
git clone https://github.com/hazelcast/hazelcast.git && \
git clone https://github.com/phax/ph-commons.git && \
git clone https://github.com/opencadc/caom2db.git && \
git clone https://github.com/KDE/kdeconnect-android.git && \
git clone https://github.com/GreenDelta/olca-modules.git && \
git clone https://github.com/Metatavu/edelphi.git && \
git clone https://github.com/spring-cloud/spring-cloud-commons.git && \
git clone https://github.com/alkacon/opencms-core.git && \
git clone https://github.com/molgenis/molgenis.git && \
git clone https://github.com/slartus/4pdaClient-plus.git && \
git clone https://github.com/Neamar/KISS.git && \
git clone https://github.com/TeamLapen/Vampirism.git && \
git clone https://github.com/MaridProject/marid.git && \
git clone https://github.com/igniterealtime/Smack.git && \
git clone https://github.com/zeroc-ice/ice-demos.git && \
git clone https://github.com/webfirmframework/wff.git && \
git clone https://github.com/mzmine/mzmine3.git && \
git clone https://github.com/nielsbasjes/yauaa.git && \
git clone https://github.com/fabric8io/kubernetes-client.git && \
git clone https://github.com/zstackio/zstack.git && \
git clone https://github.com/Tanaguru/Tanaguru.git && \
git clone https://github.com/diffplug/spotless.git && \
git clone https://github.com/savoirfairelinux/ring-client-android.git && \
git clone https://github.com/reportportal/service-api.git && \
git clone https://github.com/wso2/carbon-data.git && \
git clone https://github.com/GreenDelta/olca-app.git && \
git clone https://github.com/sk89q/CommandHelper.git && \
git clone https://github.com/gurkenlabs/litiengine.git && \
git clone https://github.com/kieker-monitoring/kieker.git && \
git clone https://github.com/raphw/byte-buddy.git && \
git clone https://github.com/moezbhatti/qksms.git && \
git clone https://github.com/google/ExoPlayer.git && \
git clone https://github.com/asciidoctor/asciidoctorj.git && \
git clone https://github.com/CyclopsMC/CyclopsCore.git && \
git clone https://github.com/vespa-engine/vespa.git && \
git clone https://github.com/marklogic/marklogic-contentpump.git && \
git clone https://github.com/UweTrottmann/SeriesGuide.git && \
git clone https://github.com/immutables/immutables.git && \
git clone https://github.com/redisson/redisson.git && \
git clone https://github.com/openthinclient/openthinclient-manager.git && \
git clone https://github.com/Javlo/javlo.git && \
git clone https://github.com/apache/commons-lang.git && \
git clone https://github.com/dhis2/dhis2-android-sdk.git && \
git clone https://github.com/bazelbuild/bazel.git && \
git clone https://github.com/MineLittlePony/MineLittlePony.git && \
git clone https://github.com/otavanopisto/pyramus.git && \
git clone https://github.com/pentaho/big-data-plugin.git && \
git clone https://github.com/IntellectualSites/PlotSquared.git && \
git clone https://github.com/tananaev/traccar.git && \
git clone https://github.com/lucee/Lucee.git && \
git clone https://github.com/popkit/pelpa.git && \
git clone https://github.com/GoldenGnu/jeveassets.git && \
git clone https://github.com/Nastel/tnt4j-streams.git && \
git clone https://github.com/ctripcorp/x-pipe.git && \
git clone https://github.com/structr/structr.git && \
git clone https://github.com/apache/camel.git && \
git clone https://github.com/gravitee-io/gravitee-gateway.git && \
git clone https://github.com/codecentric/spring-boot-admin.git && \
git clone https://github.com/mini2Dx/mini2Dx.git && \
git clone https://github.com/RoboZonky/robozonky.git && \
git clone https://github.com/fogbeam/zeppelin_mirror.git && \
git clone https://github.com/forrestguice/SuntimesWidget.git && \
git clone https://github.com/TheBusyBiscuit/Slimefun4.git && \
git clone https://github.com/kbase/workspace_deluxe.git && \
git clone https://github.com/testcontainers/testcontainers-java.git && \
git clone https://github.com/JetBrains/xodus.git && \
git clone https://github.com/apache/incubator-shardingsphere.git && \
git clone https://github.com/phenotips/patient-network.git && \
git clone https://github.com/eclipse/kapua.git && \
git clone https://github.com/jenetics/jenetics.git && \
git clone https://github.com/batfish/batfish.git && \
git clone https://github.com/kbase/njs_wrapper.git && \
git clone https://github.com/ibissource/iaf.git && \
git clone https://github.com/powsybl/powsybl-core.git && \
git clone https://github.com/openforis/collect.git && \
git clone https://github.com/wildfly-swarm/wildfly-swarm.git && \
git clone https://github.com/cadpage/cadpage-parsers.git && \
git clone https://github.com/svenkubiak/mangooio.git && \
git clone https://github.com/timmolter/XChange.git && \
git clone https://github.com/Hack23/cia.git && \
git clone https://github.com/OPENDAP/olfs.git && \
git clone https://github.com/kryptnostic/rhizome.git && \
git clone https://github.com/graknlabs/grakn.git && \
git clone https://github.com/UniTime/unitime.git && \
git clone https://github.com/PrinceOfAmber/CyclicMagic.git && \
git clone https://github.com/f-droid/fdroidclient.git && \
git clone https://github.com/real-logic/Aeron.git && \
git clone https://github.com/tlaplus/tlaplus.git && \
git clone https://github.com/TechEmpower/FrameworkBenchmarks.git && \
git clone https://github.com/jtablesaw/tablesaw.git && \
git clone https://github.com/xwiki/xwiki-commons.git && \
git clone https://github.com/splicemachine/spliceengine.git && \
git clone https://github.com/jpschewe/fll-sw.git && \
git clone https://github.com/google/closure-compiler.git && \
git clone https://github.com/kiegroup/droolsjbpm-integration.git && \
git clone https://github.com/crate/crate.git && \
git clone https://github.com/lukehutch/fast-classpath-scanner.git && \
git clone https://github.com/spacewalkproject/spacewalk.git && \
git clone https://github.com/callakrsos/Gargoyle.git && \
git clone https://github.com/SpoonLabs/astor.git && \
git clone https://github.com/SonarSource/sonarqube.git && \
git clone https://github.com/BrunoEberhard/minimal-j.git && \
git clone https://github.com/gravitee-io/gravitee-management-rest-api.git && \
git clone https://github.com/flutter/flutter-intellij.git && \
git clone https://github.com/cismet/cids-custom-wuppertal.git && \
git clone https://github.com/ZeXtras/OpenZAL.git && \
git clone https://github.com/lessthanoptimal/BoofCV.git && \
git clone https://github.com/wso2/carbon-apimgt.git && \
git clone https://github.com/b3dgs/lionengine.git && \
git clone https://github.com/PLOS/wombat.git && \
git clone https://github.com/spring-projects/spring-boot.git && \
git clone https://github.com/AVnetWS/Hentoid.git && \
git clone https://github.com/languagetool-org/languagetool.git && \
git clone https://github.com/cismet/cids-custom-wuppertal-server.git && \
git clone https://github.com/akvo/akvo-flow.git && \
git clone https://github.com/Graylog2/graylog2-server.git && \
git clone https://github.com/scoophealth/oscar.git && \
git clone https://github.com/wso2-extensions/identity-governance.git && \
git clone https://github.com/neo4j-contrib/neo4j-apoc-procedures.git && \
git clone https://github.com/CylonicRaider/Instant.git && \
git clone https://github.com/webanno/webanno.git && \
git clone https://github.com/wildfly/wildfly.git && \
git clone https://github.com/metasfresh/metasfresh-webui-api.git && \
git clone https://github.com/braintree/braintree_android.git && \
git clone https://github.com/metaborg/nabl.git && \
git clone https://github.com/Jasig/uPortal.git && \
git clone https://github.com/Whiley/WhileyCompiler.git && \
git clone https://github.com/reactor/reactor-core.git && \
git clone https://github.com/synthetichealth/synthea.git && \
git clone https://github.com/exch-bms2/beatoraja.git && \
git clone https://github.com/prestodb/presto.git && \
git clone https://github.com/servinglynk/servinglynk-hmis.git && \
git clone https://github.com/Transkribus/TranskribusSwtGui.git && \
git clone https://github.com/consulo/consulo.git && \
git clone https://github.com/apache/activemq-artemis.git && \
git clone https://github.com/graalvm/fastr.git && \
git clone https://github.com/dropwizard/dropwizard.git && \
git clone https://github.com/softindex/datakernel.git && \
git clone https://github.com/javers/javers.git && \
git clone https://github.com/sarl/sarl.git && \
git clone https://github.com/MilosKozak/AndroidAPS.git && \
git clone https://github.com/seven332/EhViewer.git && \
git clone https://github.com/pegasus-isi/pegasus.git && \
git clone https://github.com/react-native-community/react-native-svg.git && \
git clone https://github.com/xwiki/xwiki-platform.git && \
git clone https://github.com/MyCATApache/Mycat-Server.git && \
git clone https://github.com/SpongePowered/SpongeCommon.git && \
git clone https://github.com/GerritCodeReview/gerrit.git && \
git clone https://github.com/apache/wicket.git && \
git clone https://github.com/exteso/alf.io.git && \
git clone https://github.com/vert-x3/vertx-web.git && \
git clone https://github.com/dita-ot/dita-ot.git && \
git clone https://github.com/ilscipio/scipio-erp.git && \
git clone https://github.com/opendaylight/yangtools.git && \
git clone https://github.com/ankidroid/Anki-Android.git && \
git clone https://github.com/igvteam/igv.git && \
git clone https://github.com/apache/calcite.git && \
git clone https://github.com/factoryfx/factoryfx.git && \
git clone https://github.com/FINRAOS/herd.git && \
git clone https://github.com/wbaumann/SmartReceiptsLibrary.git && \
git clone https://github.com/Netflix/genie.git && \
git clone https://github.com/square/okhttp.git && \
git clone https://github.com/pac4j/pac4j.git && \
git clone https://github.com/openbase/jul.git && \
git clone https://github.com/elki-project/elki.git && \
git clone https://github.com/telefonicaid/fiware-cygnus.git && \
git clone https://github.com/tvesalainen/util.git && \
git clone https://github.com/apache/accumulo.git && \
git clone https://github.com/joel-costigliola/assertj-core.git && \
git clone https://github.com/stupidsing/suite.git && \
git clone https://github.com/wyvernlang/wyvern.git && \
git clone https://github.com/ac2cz/FoxTelem.git && \
git clone https://github.com/SCADA-LTS/Scada-LTS.git && \
git clone https://github.com/DeviceConnect/DeviceConnect-Android.git && \
git clone https://github.com/jaamsim/jaamsim.git && \
git clone https://github.com/WhisperSystems/TextSecure.git && \
git clone https://github.com/AnySoftKeyboard/AnySoftKeyboard.git && \
git clone https://github.com/SilentChaos512/SilentGems.git && \
git clone https://github.com/apache/beam.git && \
git clone https://github.com/estatio/estatio.git && \
git clone https://github.com/apache/uima-uimaj.git && \
git clone https://github.com/marklogic/java-client-api.git && \
git clone https://github.com/project-ncl/pnc.git && \
git clone https://github.com/treasure-data/digdag.git && \
git clone https://github.com/spring-cloud/spring-cloud-stream.git && \
git clone https://github.com/fogbeam/cas_mirror.git && \
git clone https://github.com/Jasig/cas.git && \
git clone https://github.com/oncokb/oncokb.git && \
git clone https://github.com/TechReborn/RebornCore.git && \
git clone https://github.com/breadwallet/breadwallet-android.git && \
git clone https://github.com/endeavourhealth/EDS.git && \
git clone https://github.com/ProtocolSupport/ProtocolSupport.git && \
git clone https://github.com/apache/sis.git && \
git clone https://github.com/GoogleCloudPlatform/java-docs-samples.git && \
git clone https://github.com/undertow-io/undertow.git && \
git clone https://github.com/openmicroscopy/bioformats.git && \
git clone https://github.com/TechReborn/TechReborn.git && \
git clone https://github.com/commons-app/apps-android-commons.git && \
git clone https://github.com/giiwa/giiwa.git && \
git clone https://github.com/theScrabi/NewPipe.git && \
git clone https://github.com/beast-dev/beast-mcmc.git && \
git clone https://github.com/folio-org/okapi.git && \
git clone https://github.com/opencb/opencga.git && \
git clone https://github.com/Aptoide/aptoide-client-v8.git && \
git clone https://github.com/actframework/actframework.git && \
git clone https://github.com/graphhopper/graphhopper.git && \
git clone https://github.com/liquibase/liquibase.git && \
git clone https://github.com/druid-io/druid.git && \
git clone https://github.com/blackducksoftware/hub-jira.git && \
git clone https://github.com/linkedin/ambry.git && \
git clone https://github.com/GluuFederation/oxTrust.git && \
git clone https://github.com/EnMasseProject/enmasse.git && \
git clone https://github.com/watson-developer-cloud/java-sdk.git && \
git clone https://github.com/FreeCol/freecol.git && \
git clone https://github.com/wso2/siddhi.git && \
git clone https://github.com/sdl/dxa-web-application-java.git && \
git clone https://github.com/php-coder/mystamps.git && \
git clone https://github.com/winder/Universal-G-Code-Sender.git && \
git clone https://github.com/facebook/fresco.git && \
git clone https://github.com/dzhw/metadatamanagement.git && \
git clone https://github.com/mlhartme/stool.git && \
git clone https://github.com/neo4j/neo4j-java-driver.git && \
git clone https://github.com/IBMStreams/streamsx.topology.git && \
git clone https://github.com/apache/groovy.git && \
git clone https://github.com/andstatus/andstatus.git && \
git clone https://github.com/apache/drill.git && \
git clone https://github.com/KonkerLabs/konker-platform.git && \
git clone https://github.com/arnaudroger/SimpleFlatMapper.git && \
git clone https://github.com/googleapis/java-bigtable-hbase.git && \
git clone https://github.com/hneemann/Digital.git && \
git clone https://github.com/Alfresco/alfresco-repository.git && \
git clone https://github.com/workcraft/workcraft.git && \
git clone https://github.com/CloudSlang/cs-actions.git && \
git clone https://github.com/mercadopago/px-android.git && \
git clone https://github.com/igniterealtime/Openfire.git && \
git clone https://github.com/line/armeria.git && \
git clone https://github.com/esig/dss.git && \
git clone https://github.com/yamcs/yamcs.git && \
git clone https://github.com/hazelcast/hazelcast-jet.git && \
git clone https://github.com/exedio/persistence.git && \
git clone https://github.com/cerberustesting/cerberus-source.git && \
git clone https://github.com/Peergos/Peergos.git && \
git clone https://github.com/wikimedia/apps-android-wikipedia.git && \
git clone https://github.com/InnovateUKGitHub/innovation-funding-service.git && \
git clone https://github.com/google/guava.git && \
git clone https://github.com/arquivo/functional-tests.git && \
git clone https://github.com/cytoscape/cytoscape-impl.git && \
git clone https://github.com/nextcloud/android.git && \
git clone https://github.com/apache/logging-log4j2.git && \
git clone https://github.com/orientechnologies/orientdb.git && \
git clone https://github.com/opennetworkinglab/onos.git && \
git clone https://github.com/umple/umple.git && \
git clone https://github.com/validator/validator.git && \
git clone https://github.com/FenixEdu/fenixedu-academic.git && \
git clone https://github.com/googleapis/google-cloud-java.git && \
git clone https://github.com/mesosphere/dcos-commons.git && \
git clone https://github.com/LWJGL/lwjgl3.git && \
git clone https://github.com/nemerosa/ontrack.git && \
git clone https://github.com/conveyal/r5.git && \
git clone https://github.com/apache/pdfbox.git && \
git clone https://github.com/google/error-prone.git && \
git clone https://github.com/opendaylight/controller.git && \
git clone https://github.com/mars-sim/mars-sim.git && \
git clone https://github.com/apache/syncope.git && \
git clone https://github.com/xXKeyleXx/MyPet.git && \
git clone https://github.com/jitsi/jitsi-videobridge.git && \
git clone https://github.com/siacs/Conversations.git && \
git clone https://github.com/SleepyTrousers/EnderIO.git && \
git clone https://github.com/kickstarter/android-oss.git && \
git clone https://github.com/ow2-proactive/scheduling.git && \
git clone https://github.com/CyclopsMC/IntegratedDynamics.git && \
git clone https://github.com/BorderTech/wcomponents.git && \
git clone https://github.com/jeremylong/DependencyCheck.git && \
git clone https://github.com/kiegroup/drools.git && \
git clone https://github.com/apache/kylin.git && \
git clone https://github.com/sosy-lab/java-smt.git && \
git clone https://github.com/openpnp/openpnp.git && \
git clone https://github.com/apache/ignite.git && \
git clone https://github.com/MariaDB/mariadb-connector-j.git && \
git clone https://github.com/GluuFederation/oxAuth.git && \
git clone https://github.com/vroyer/elassandra.git && \
git clone https://github.com/wix/react-native-navigation.git && \
git clone https://github.com/google/copybara.git && \
git clone https://github.com/spring-cloud/spring-cloud-dataflow.git && \
git clone https://github.com/wso2/carbon-business-process.git && \
git clone https://github.com/langurmonkey/gaiasky.git && \
git clone https://github.com/henrichg/PhoneProfiles.git && \
git clone https://github.com/apache/jackrabbit-oak.git && \
git clone https://github.com/robolectric/robolectric.git && \
git clone https://github.com/sklintyg/webcert.git && \
git clone https://github.com/jamorham/xDrip-plus.git && \
git clone https://github.com/HubSpot/Singularity.git && \
git clone https://github.com/openzipkin/zipkin.git && \
git clone https://github.com/raoulvdberge/refinedstorage.git && \
git clone https://github.com/AntennaPod/AntennaPod.git && \
git clone https://github.com/google/nomulus.git && \
git clone https://github.com/Azure/azure-sdk-for-java.git && \
git clone https://github.com/MyCoRe-Org/mycore.git && \
git clone https://github.com/strongbox/strongbox.git && \
git clone https://github.com/zaproxy/zap-extensions.git && \
git clone https://github.com/opendaylight/netvirt.git && \
git clone https://github.com/md-5/jdk10.git && \
git clone https://github.com/dhis2/dhis2-core.git && \
git clone https://github.com/spring-projects/spring-security.git && \
git clone https://github.com/SeleniumHQ/selenium.git && \
git clone https://github.com/inaturalist/iNaturalistAndroid.git && \
git clone https://github.com/jenkinsci/jenkins.git && \
git clone https://github.com/apache/phoenix.git && \
git clone https://github.com/phac-nml/irida.git && \
git clone https://github.com/calipho-sib/nextprot-api.git && \
git clone https://github.com/zalando/nakadi.git && \
git clone https://github.com/streamsets/datacollector.git && \
git clone https://github.com/bcvsolutions/CzechIdMng.git && \
git clone https://github.com/pravega/pravega.git && \
git clone https://github.com/OpenHFT/Chronicle-Queue.git && \
git clone https://github.com/oaplatform/oap.git && \
git clone https://github.com/Commonjava/indy.git && \
git clone https://github.com/k9mail/k-9.git && \
git clone https://github.com/bozimmerman/CoffeeMud.git && \
git clone https://github.com/netty/netty.git && \
git clone https://github.com/facebook/buck.git && \
git clone https://github.com/NYRDS/pixel-dungeon-remix.git && \
git clone https://github.com/MyRobotLab/myrobotlab.git && \
git clone https://github.com/apache/cassandra.git && \
git clone https://github.com/h2oai/h2o-3.git && \
git clone https://github.com/micromata/projectforge.git && \
git clone https://github.com/SpongePowered/SpongeForge.git && \
git clone https://github.com/mockito/mockito.git && \
git clone https://github.com/apache/flink.git && \
git clone https://github.com/broadinstitute/gatk.git && \
git clone https://github.com/pentaho/pentaho-kettle.git && \
git clone https://github.com/keycloak/keycloak.git && \
git clone https://github.com/OpenGamma/Strata.git && \
git clone https://github.com/linkedin/pinot.git && \
git clone https://github.com/edx/edx-app-android.git && \
git clone https://github.com/geotools/geotools.git && \
git clone https://github.com/flowable/flowable-engine.git && \
git clone https://github.com/khartec/waltz.git && \
git clone https://github.com/DV8FromTheWorld/JDA.git && \
git clone https://github.com/Alluxio/alluxio.git && \
git clone https://github.com/openhab/openhab2.git && \
git clone https://github.com/tuomount/Open-Realms-of-Stars.git && \
git clone https://github.com/aosp-mirror/platform_frameworks_support.git && \
git clone https://github.com/Yakindu/statecharts.git && \
git clone https://github.com/bendisposto/prob2-ui.git && \
git clone https://github.com/lamsfoundation/lams.git && \
git clone https://github.com/couchbase/couchbase-lite-android.git && \
git clone https://github.com/FAForever/downlords-faf-client.git && \
git clone https://github.com/Alfresco/records-management.git && \
git clone https://github.com/google/j2objc.git && \
git clone https://github.com/JabRef/jabref.git && \
git clone https://github.com/ontop/ontop.git && \
git clone https://github.com/wso2/devstudio-tooling-esb.git && \
git clone https://github.com/austinv11/Discord4J.git && \
git clone https://github.com/sleuthkit/autopsy.git && \
git clone https://github.com/iterate-ch/cyberduck.git && \
git clone https://github.com/jnidzwetzki/bboxdb.git && \
git clone https://github.com/cgeo/cgeo.git && \
git clone https://github.com/CESNET/perun.git && \
git clone https://github.com/b2ihealthcare/snow-owl.git && \
git clone https://github.com/eXist-db/exist.git && \
git clone https://github.com/joinfaces/joinfaces.git && \
git clone https://github.com/hortonworks/cloudbreak.git && \
git clone https://github.com/Activiti/Activiti.git && \
git clone https://github.com/00-Evan/shattered-pixel-dungeon.git && \
git clone https://github.com/Minecolonies/minecolonies.git && \
git clone https://github.com/crapo/sadlos2.git && \
git clone https://github.com/wordpress-mobile/WordPress-FluxC-Android.git && \
git clone https://github.com/gocd/gocd.git && \
git clone https://github.com/ctripcorp/apollo.git && \
git clone https://github.com/junit-team/junit-lambda.git && \
git clone https://github.com/gama-platform/gama.git && \
git clone https://github.com/grpc/grpc-java.git && \
git clone https://github.com/Sage-Bionetworks/Synapse-Repository-Services.git && \
git clone https://github.com/alibaba/fastjson.git && \
git clone https://github.com/elBukkit/MagicPlugin.git && \
git clone https://github.com/kriztan/Pix-Art-Messenger.git && \
git clone https://github.com/kontalk/androidclient.git && \
git clone https://github.com/ISISComputingGroup/ibex_gui.git && \
git clone https://github.com/naver/pinpoint.git && \
git clone https://github.com/material-components/material-components-android.git && \
git clone https://github.com/triplea-game/triplea.git && \
git clone https://github.com/imCodePartnerAB/imcms.git && \
git clone https://github.com/apache/hadoop.git && \
git clone https://github.com/waikato-datamining/adams-base.git